[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_speed = 74880
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson

build_flags =
    -Wall
    -D APP_VERSION=\"0.5.3-ota-update\"

[env:d1_mini_ota]
extends = env:d1_mini
upload_protocol = espota
upload_port = 192.168.10.44

; If security.apiAuthEnabled=true and security.apiToken is set,
; use the same token as OTA password:
; upload_flags =
;     --auth=change-this-token
